# eureka配置 客户端配置，注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: 60000
        max-idle: 8
        min-idle: 1
    timeout: 10000
  # mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://47.107.184.79:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: ljhLargeQuant9466!
      driver-class-name: com.mysql.cj.jdbc.Driver
      stat-view-servlet:
        login-username: admin
        login-password: admin
        enabled: true
        url-pattern: /druid/*
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      query-timeout: 90
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          db-type: mysql
          merge-sql: false
        wall:
          config:
            delete-allow: false
            drop-table-allow: false
          enabled: true
          db-type: mysql
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true

# mybatisPlus配置
mybatis-plus:
  mapper-locations: classpath*:/mybatis-mappers/*
  type-aliases-package: cn.largequant.cloudcommon.entity
  configuration:
    map-underscore-to-camel-case: true