# eureka配置 客户端配置，注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  # redis配置
  redis:
    # 选择redis的第几号数据库
    database: 0
    # 服务器
    host: 127.0.0.1
    # 端口
    port: 6379
    # 密码
    password: 123456
    # 连接池
    lettuce:
      pool:
        # 最大连接数 (负数代表无限制)
        max-active: 8
        # 连接池最大阻塞时间 (ms) (负数代表无限制)
        max-wait: 60000
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 1
    # 连接超时时间 (ms)
    timeout: 10000
  # mysql配置
  datasource:
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化druid
    druid:
      # jdbc基础配置
      url: jdbc:mysql://127.0.0.1:3306/ywh_code?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 监控页面的用户名和密码 以及页面地址
      stat-view-servlet:
        login-username: admin
        login-password: admin
        enabled: true
        url-pattern: /druid/*
      # Initialize the connection size 。Default: 0
      initial-size: 5
      # Minimum number of idle connections 。Default: 0
      min-idle: 5
      # Maximum number of connections 。Default: 8
      max-active: 20
      # Get the connection wait timeout (ms) 。Default: -1
      max-wait: 60000
      # Query timeout (seconds)
      query-timeout: 90
      # Sql used to detect whether the connection is valid, the request is a query statement
      validation-query: SELECT 1 FROM DUAL
      # Check connection availability when applying for a connection 。Default: false
      test-on-borrow: false
      # Return Connection Detection 。Default: false
      test-on-return: false
      # Whether the timeout detects connection availability
      test-while-idle: true
      # How long does the configuration interval take to detect an idle connection (milliseconds) that needs to be closed?
      time-between-eviction-runs-millis: 60000
      # Configure the minimum lifetime of a connection in the pool (ms, default 30 minutes)
      min-evictable-idle-time-millis: 300000
      # Configure extensions by alias. Common plug-ins are: filter:stat for monitoring statistics; filter:log4j for logs; filter:wall for sql injection
      filters: stat,wall,slf4j
      # Slow SQL record https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          db-type: mysql
          # SQL merge Default: false
          merge-sql: false
        wall:
          config:
            delete-allow: false
            drop-table-allow: false
          enabled: true
          db-type: mysql
      # Whether to cache PreparedStatement. PSCache has a huge performance improvement on the database that supports cursors, for example, oracle. It is recommended to close under mysql.
      pool-prepared-statements: false
      # The size of the PSCache on each connection
      max-pool-prepared-statement-per-connection-size: 20
      # Combine monitoring data from multiple DruidDataSources
      use-global-data-source-stat: true

# mybatisPlus配置
mybatis-plus:
  # 指定mapper.xml位置
  mapper-locations: classpath*:/mybatis-mappers/*
  # mybaits别名包扫描路径
  type-aliases-package: cn.largequant.cloudcommon.entity
  # 数据库表与实体类驼峰命名的自动转换
  configuration:
    map-underscore-to-camel-case: true