# eureka配置 客户端配置，注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# zuul 配置
zuul:
  routes:
    api-a:
      path: /cloud-core/**
      serviceId: cloud-core
    api-b:
      # Zuul网关会替我们负载均衡的来访问接口
      path: /cloud-auth/**
      # Zuul识别的服务id
      serviceId: cloud-auth